name: CI Pipeline

on:
  push:
    branches:
      - main
      - developer
      - feat/setup/workflows

  pull_request:
    branches:
      - main
      - developer

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Build and test in backend folder
        run: |
          cd ./backend
          chmod +x ./mvnw
          ./mvnw clean install
          ./mvnw test